approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

packageExtensions:
  vite-plugin-dts@5.1.0:
    dependencies:
      typescript: "npm:@typescript/typescript6@^6.0.2"
